version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: book-catalog-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: book-catalog-db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: